/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.uw.edm.docfinity;

import org.junit.Test;
import static org.junit.Assert.*;

public class DocFinityClientTest {
    @Test public void testSomeLibraryMethod() {
        DocFinityClient classUnderTest = new DocFinityClient();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
