/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.uw.edm.docfinity;

public class DocFinityClient {
    public boolean someLibraryMethod() {
        return true;
    }
}
